### ISSUE TITLE
publish the emoji json as a separate lib

### ISSUE THREAD

**Issue by Haroenv** [eliasmeire/emoji-pane#1]
Since all other emoji libraries don't have the necessary metadata, it could be called `emoji-data` or `emoji-max` or similar

**Comment by elsmr** [comment]
Maybe, but the json i use is basically the one from the emojione repo. I don't think it's a good idea to publish their data.

**Comment by Haroenv** [comment]
good point I guess, there’s definitely need for an emoji dataset with loads of keywords though
